stages:
  data_ingestion:
    cmd: python src/components/data_ingestion.py
    deps:
    - src/components/data_ingestion.py
    params:
    - data_ingestion.test_size
    outs:
    - data/raw
  data_preprocessing:
    cmd: python src/components/data_preprocessing.py
    deps:
    - data/raw
    - src/components/data_preprocessing.py
    outs:
    - data/preprocess
  feature_engineering:
    cmd: python src/components/feature_engineering.py
    deps:
    - data/preprocess
    - src/components/feature_engineering.py
    params:
    - feature_engineering.max_features
    outs:
    - data/processed_final
  model_building:
    cmd: python src/components/model_building.py
    deps:
    - data/processed_final
    - src/components/model_building.py
    params:
    - model_building.n_estimators
    - model_building.random_state
    outs:
    - models/model.pkl
  model_evaluation:
    cmd: python src/components/model_evaluation.py
    deps:
    - models/model.pkl
    - src/components/model_evaluation.py
    metrics:
    - reports/metrics.json
params:
- dvclive/params.yaml
metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
